version: '3.9'
services:
  mqtt_rust_pubsub:
    restart: always
    build: ./rust-mqtt-pubsub/.
    links:
      - artemis
    environment:
      RUST_LOG: debug
      MQTT_HOST: artemis
      MQTT_PORT: 1883
      MQTT_USERNAME: root
      MQTT_PASSWORD: root
      MQTT_TOPIC_SUBSCRIPTION: mqtt_topic
      MQTT_TOPIC_PUBLISHING: jms_topic
  mqtt_nodejs_publisher:
    restart: always
    build: ./nodejs-mqtt-publisher/.  
    links:
      - artemis
    environment:
      MQTT_HOST: artemis
      MQTT_PORT: 1883
      MQTT_USERNAME: root
      MQTT_PASSWORD: root
      MQTT_TOPIC_PUBLISHING: mqtt_topic